# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
        ('photologue', '0012_auto_20150724_0109'),
    ]

    operations = [
    ]
